import { Configure, GenericTypeGuard, GenericValidator } from 'runtime-typescript-checker';
import { DancerInterface, eRole, DanceClass } from './dances';

// ** THIS FILE IS AUTOGENERATED; DO NOT CHANGE.

export { Configure };

export function ValidateDancerInterface(iCandidate: unknown): ReturnType<typeof GenericValidator> {
   return GenericValidator("DancerInterface", iCandidate);
}

export function IsDancerInterface(iCandidate: unknown): iCandidate is DancerInterface {
   return GenericTypeGuard("DancerInterface", iCandidate);
}

export function ValidateeRole(iCandidate: unknown): ReturnType<typeof GenericValidator> {
   return GenericValidator("eRole", iCandidate);
}

export function IseRole(iCandidate: unknown): iCandidate is eRole {
   return GenericTypeGuard("eRole", iCandidate);
}

export function ValidateDanceClass(iCandidate: unknown): ReturnType<typeof GenericValidator> {
   return GenericValidator("DanceClass", iCandidate);
}

export function IsDanceClass(iCandidate: unknown): iCandidate is DanceClass {
   return GenericTypeGuard("DanceClass", iCandidate);
}
